### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by simonpoole** [simon04/whodidit#13]
Seems as if the service is currently not working: web ui appears but no data.

What kind of HW requirements does the service currently have? It would seem to be a good idea to move it to something more permament than the dev server.

**Comment by simon04** [comment]
I guess this was a load / timeout issue. In order to improve the performance, I restricted the data to ≈80 days (i.e., since 2015-01-01) manually. An enhancement would be to either query the current, small dataset of a few months or the "archive" table with a longer time range …

Concerning requirements: The data since 2015-01-01 needs about 1.2 GB for the MySQL tables (data_length + index_length) …
